#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mobile_hardware")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertvm_brand(vm_brand instance);
  partial void Updatevm_brand(vm_brand instance);
  partial void Deletevm_brand(vm_brand instance);
  partial void Insertvm_userinfo(vm_userinfo instance);
  partial void Updatevm_userinfo(vm_userinfo instance);
  partial void Deletevm_userinfo(vm_userinfo instance);
  partial void Insertvm_category(vm_category instance);
  partial void Updatevm_category(vm_category instance);
  partial void Deletevm_category(vm_category instance);
  partial void Insertvm_order_buy(vm_order_buy instance);
  partial void Updatevm_order_buy(vm_order_buy instance);
  partial void Deletevm_order_buy(vm_order_buy instance);
  partial void Insertvm_orderlist(vm_orderlist instance);
  partial void Updatevm_orderlist(vm_orderlist instance);
  partial void Deletevm_orderlist(vm_orderlist instance);
  partial void Insertvm_pic(vm_pic instance);
  partial void Updatevm_pic(vm_pic instance);
  partial void Deletevm_pic(vm_pic instance);
  partial void Insertvm_product(vm_product instance);
  partial void Updatevm_product(vm_product instance);
  partial void Deletevm_product(vm_product instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mobile_hardwareConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<vm_brand> vm_brands
	{
		get
		{
			return this.GetTable<vm_brand>();
		}
	}
	
	public System.Data.Linq.Table<vm_userinfo> vm_userinfos
	{
		get
		{
			return this.GetTable<vm_userinfo>();
		}
	}
	
	public System.Data.Linq.Table<vm_category> vm_categories
	{
		get
		{
			return this.GetTable<vm_category>();
		}
	}
	
	public System.Data.Linq.Table<vm_order_buy> vm_order_buys
	{
		get
		{
			return this.GetTable<vm_order_buy>();
		}
	}
	
	public System.Data.Linq.Table<vm_orderlist> vm_orderlists
	{
		get
		{
			return this.GetTable<vm_orderlist>();
		}
	}
	
	public System.Data.Linq.Table<vm_pic> vm_pics
	{
		get
		{
			return this.GetTable<vm_pic>();
		}
	}
	
	public System.Data.Linq.Table<vm_product> vm_products
	{
		get
		{
			return this.GetTable<vm_product>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vm_brand")]
public partial class vm_brand : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _name;
	
	private EntitySet<vm_product> _vm_products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
	
	public vm_brand()
	{
		this._vm_products = new EntitySet<vm_product>(new Action<vm_product>(this.attach_vm_products), new Action<vm_product>(this.detach_vm_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_brand_vm_product", Storage="_vm_products", ThisKey="id", OtherKey="brand_id")]
	public EntitySet<vm_product> vm_products
	{
		get
		{
			return this._vm_products;
		}
		set
		{
			this._vm_products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_vm_products(vm_product entity)
	{
		this.SendPropertyChanging();
		entity.vm_brand = this;
	}
	
	private void detach_vm_products(vm_product entity)
	{
		this.SendPropertyChanging();
		entity.vm_brand = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vm_userinfo")]
public partial class vm_userinfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _user_name;
	
	private string _password;
	
	private string _f_name;
	
	private string _l_name;
	
	private string _email;
	
	private string _address;
	
	private string _mobile;
	
	private string _phone;
	
	private string _zip_code;
	
	private string _company;
	
	private System.Nullable<bool> _is_admin;
	
	private System.Nullable<short> _percent_price;
	
	private System.Nullable<bool> _is_off;
	
	private System.Nullable<short> _ostan;
	
	private System.Nullable<short> _city;
	
	private EntitySet<vm_order_buy> _vm_order_buys;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onf_nameChanging(string value);
    partial void Onf_nameChanged();
    partial void Onl_nameChanging(string value);
    partial void Onl_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onzip_codeChanging(string value);
    partial void Onzip_codeChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void Onis_adminChanging(System.Nullable<bool> value);
    partial void Onis_adminChanged();
    partial void Onpercent_priceChanging(System.Nullable<short> value);
    partial void Onpercent_priceChanged();
    partial void Onis_offChanging(System.Nullable<bool> value);
    partial void Onis_offChanged();
    partial void OnostanChanging(System.Nullable<short> value);
    partial void OnostanChanged();
    partial void OncityChanging(System.Nullable<short> value);
    partial void OncityChanged();
    #endregion
	
	public vm_userinfo()
	{
		this._vm_order_buys = new EntitySet<vm_order_buy>(new Action<vm_order_buy>(this.attach_vm_order_buys), new Action<vm_order_buy>(this.detach_vm_order_buys));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string user_name
	{
		get
		{
			return this._user_name;
		}
		set
		{
			if ((this._user_name != value))
			{
				this.Onuser_nameChanging(value);
				this.SendPropertyChanging();
				this._user_name = value;
				this.SendPropertyChanged("user_name");
				this.Onuser_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_name", DbType="NVarChar(20)")]
	public string f_name
	{
		get
		{
			return this._f_name;
		}
		set
		{
			if ((this._f_name != value))
			{
				this.Onf_nameChanging(value);
				this.SendPropertyChanging();
				this._f_name = value;
				this.SendPropertyChanged("f_name");
				this.Onf_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_name", DbType="NVarChar(20)")]
	public string l_name
	{
		get
		{
			return this._l_name;
		}
		set
		{
			if ((this._l_name != value))
			{
				this.Onl_nameChanging(value);
				this.SendPropertyChanging();
				this._l_name = value;
				this.SendPropertyChanged("l_name");
				this.Onl_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(15)")]
	public string mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(15)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip_code", DbType="NVarChar(15)")]
	public string zip_code
	{
		get
		{
			return this._zip_code;
		}
		set
		{
			if ((this._zip_code != value))
			{
				this.Onzip_codeChanging(value);
				this.SendPropertyChanging();
				this._zip_code = value;
				this.SendPropertyChanged("zip_code");
				this.Onzip_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(20)")]
	public string company
	{
		get
		{
			return this._company;
		}
		set
		{
			if ((this._company != value))
			{
				this.OncompanyChanging(value);
				this.SendPropertyChanging();
				this._company = value;
				this.SendPropertyChanged("company");
				this.OncompanyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_admin", DbType="Bit")]
	public System.Nullable<bool> is_admin
	{
		get
		{
			return this._is_admin;
		}
		set
		{
			if ((this._is_admin != value))
			{
				this.Onis_adminChanging(value);
				this.SendPropertyChanging();
				this._is_admin = value;
				this.SendPropertyChanged("is_admin");
				this.Onis_adminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percent_price", DbType="SmallInt")]
	public System.Nullable<short> percent_price
	{
		get
		{
			return this._percent_price;
		}
		set
		{
			if ((this._percent_price != value))
			{
				this.Onpercent_priceChanging(value);
				this.SendPropertyChanging();
				this._percent_price = value;
				this.SendPropertyChanged("percent_price");
				this.Onpercent_priceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_off", DbType="Bit")]
	public System.Nullable<bool> is_off
	{
		get
		{
			return this._is_off;
		}
		set
		{
			if ((this._is_off != value))
			{
				this.Onis_offChanging(value);
				this.SendPropertyChanging();
				this._is_off = value;
				this.SendPropertyChanged("is_off");
				this.Onis_offChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ostan", DbType="SmallInt")]
	public System.Nullable<short> ostan
	{
		get
		{
			return this._ostan;
		}
		set
		{
			if ((this._ostan != value))
			{
				this.OnostanChanging(value);
				this.SendPropertyChanging();
				this._ostan = value;
				this.SendPropertyChanged("ostan");
				this.OnostanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="SmallInt")]
	public System.Nullable<short> city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_userinfo_vm_order_buy", Storage="_vm_order_buys", ThisKey="id", OtherKey="user_id")]
	public EntitySet<vm_order_buy> vm_order_buys
	{
		get
		{
			return this._vm_order_buys;
		}
		set
		{
			this._vm_order_buys.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_vm_order_buys(vm_order_buy entity)
	{
		this.SendPropertyChanging();
		entity.vm_userinfo = this;
	}
	
	private void detach_vm_order_buys(vm_order_buy entity)
	{
		this.SendPropertyChanging();
		entity.vm_userinfo = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vm_category")]
public partial class vm_category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _name;
	
	private EntitySet<vm_product> _vm_products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
	
	public vm_category()
	{
		this._vm_products = new EntitySet<vm_product>(new Action<vm_product>(this.attach_vm_products), new Action<vm_product>(this.detach_vm_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_category_vm_product", Storage="_vm_products", ThisKey="id", OtherKey="cat_id")]
	public EntitySet<vm_product> vm_products
	{
		get
		{
			return this._vm_products;
		}
		set
		{
			this._vm_products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_vm_products(vm_product entity)
	{
		this.SendPropertyChanging();
		entity.vm_category = this;
	}
	
	private void detach_vm_products(vm_product entity)
	{
		this.SendPropertyChanging();
		entity.vm_category = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vm_order_buy")]
public partial class vm_order_buy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _id;
	
	private int _user_id;
	
	private string _status;
	
	private string _peyment;
	
	private System.DateTime _date;
	
	private System.Nullable<long> _totalprice;
	
	private System.Nullable<long> _sendprice;
	
	private EntitySet<vm_orderlist> _vm_orderlists;
	
	private EntityRef<vm_userinfo> _vm_userinfo;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnpeymentChanging(string value);
    partial void OnpeymentChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OntotalpriceChanging(System.Nullable<long> value);
    partial void OntotalpriceChanged();
    partial void OnsendpriceChanging(System.Nullable<long> value);
    partial void OnsendpriceChanged();
    #endregion
	
	public vm_order_buy()
	{
		this._vm_orderlists = new EntitySet<vm_orderlist>(new Action<vm_orderlist>(this.attach_vm_orderlists), new Action<vm_orderlist>(this.detach_vm_orderlists));
		this._vm_userinfo = default(EntityRef<vm_userinfo>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
	public long id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._vm_userinfo.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(20)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peyment", DbType="NVarChar(30)")]
	public string peyment
	{
		get
		{
			return this._peyment;
		}
		set
		{
			if ((this._peyment != value))
			{
				this.OnpeymentChanging(value);
				this.SendPropertyChanging();
				this._peyment = value;
				this.SendPropertyChanged("peyment");
				this.OnpeymentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
	public System.DateTime date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalprice", DbType="BigInt")]
	public System.Nullable<long> totalprice
	{
		get
		{
			return this._totalprice;
		}
		set
		{
			if ((this._totalprice != value))
			{
				this.OntotalpriceChanging(value);
				this.SendPropertyChanging();
				this._totalprice = value;
				this.SendPropertyChanged("totalprice");
				this.OntotalpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendprice", DbType="BigInt")]
	public System.Nullable<long> sendprice
	{
		get
		{
			return this._sendprice;
		}
		set
		{
			if ((this._sendprice != value))
			{
				this.OnsendpriceChanging(value);
				this.SendPropertyChanging();
				this._sendprice = value;
				this.SendPropertyChanged("sendprice");
				this.OnsendpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_order_buy_vm_orderlist", Storage="_vm_orderlists", ThisKey="id", OtherKey="order_id")]
	public EntitySet<vm_orderlist> vm_orderlists
	{
		get
		{
			return this._vm_orderlists;
		}
		set
		{
			this._vm_orderlists.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_userinfo_vm_order_buy", Storage="_vm_userinfo", ThisKey="user_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public vm_userinfo vm_userinfo
	{
		get
		{
			return this._vm_userinfo.Entity;
		}
		set
		{
			vm_userinfo previousValue = this._vm_userinfo.Entity;
			if (((previousValue != value) 
						|| (this._vm_userinfo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._vm_userinfo.Entity = null;
					previousValue.vm_order_buys.Remove(this);
				}
				this._vm_userinfo.Entity = value;
				if ((value != null))
				{
					value.vm_order_buys.Add(this);
					this._user_id = value.id;
				}
				else
				{
					this._user_id = default(int);
				}
				this.SendPropertyChanged("vm_userinfo");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_vm_orderlists(vm_orderlist entity)
	{
		this.SendPropertyChanging();
		entity.vm_order_buy = this;
	}
	
	private void detach_vm_orderlists(vm_orderlist entity)
	{
		this.SendPropertyChanging();
		entity.vm_order_buy = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vm_orderlist")]
public partial class vm_orderlist : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private int _product_id;
	
	private long _order_id;
	
	private System.Nullable<short> _count;
	
	private EntityRef<vm_order_buy> _vm_order_buy;
	
	private EntityRef<vm_product> _vm_product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    partial void Onorder_idChanging(long value);
    partial void Onorder_idChanged();
    partial void OncountChanging(System.Nullable<short> value);
    partial void OncountChanged();
    #endregion
	
	public vm_orderlist()
	{
		this._vm_order_buy = default(EntityRef<vm_order_buy>);
		this._vm_product = default(EntityRef<vm_product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
	public int product_id
	{
		get
		{
			return this._product_id;
		}
		set
		{
			if ((this._product_id != value))
			{
				if (this._vm_product.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onproduct_idChanging(value);
				this.SendPropertyChanging();
				this._product_id = value;
				this.SendPropertyChanged("product_id");
				this.Onproduct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="BigInt NOT NULL")]
	public long order_id
	{
		get
		{
			return this._order_id;
		}
		set
		{
			if ((this._order_id != value))
			{
				if (this._vm_order_buy.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onorder_idChanging(value);
				this.SendPropertyChanging();
				this._order_id = value;
				this.SendPropertyChanged("order_id");
				this.Onorder_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="SmallInt")]
	public System.Nullable<short> count
	{
		get
		{
			return this._count;
		}
		set
		{
			if ((this._count != value))
			{
				this.OncountChanging(value);
				this.SendPropertyChanging();
				this._count = value;
				this.SendPropertyChanged("count");
				this.OncountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_order_buy_vm_orderlist", Storage="_vm_order_buy", ThisKey="order_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public vm_order_buy vm_order_buy
	{
		get
		{
			return this._vm_order_buy.Entity;
		}
		set
		{
			vm_order_buy previousValue = this._vm_order_buy.Entity;
			if (((previousValue != value) 
						|| (this._vm_order_buy.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._vm_order_buy.Entity = null;
					previousValue.vm_orderlists.Remove(this);
				}
				this._vm_order_buy.Entity = value;
				if ((value != null))
				{
					value.vm_orderlists.Add(this);
					this._order_id = value.id;
				}
				else
				{
					this._order_id = default(long);
				}
				this.SendPropertyChanged("vm_order_buy");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_product_vm_orderlist", Storage="_vm_product", ThisKey="product_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public vm_product vm_product
	{
		get
		{
			return this._vm_product.Entity;
		}
		set
		{
			vm_product previousValue = this._vm_product.Entity;
			if (((previousValue != value) 
						|| (this._vm_product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._vm_product.Entity = null;
					previousValue.vm_orderlists.Remove(this);
				}
				this._vm_product.Entity = value;
				if ((value != null))
				{
					value.vm_orderlists.Add(this);
					this._product_id = value.id;
				}
				else
				{
					this._product_id = default(int);
				}
				this.SendPropertyChanged("vm_product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vm_pic")]
public partial class vm_pic : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _product_id;
	
	private string _name;
	
	private EntityRef<vm_product> _vm_product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onproduct_idChanging(System.Nullable<int> value);
    partial void Onproduct_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
	
	public vm_pic()
	{
		this._vm_product = default(EntityRef<vm_product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int")]
	public System.Nullable<int> product_id
	{
		get
		{
			return this._product_id;
		}
		set
		{
			if ((this._product_id != value))
			{
				if (this._vm_product.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onproduct_idChanging(value);
				this.SendPropertyChanging();
				this._product_id = value;
				this.SendPropertyChanged("product_id");
				this.Onproduct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_product_vm_pic", Storage="_vm_product", ThisKey="product_id", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
	public vm_product vm_product
	{
		get
		{
			return this._vm_product.Entity;
		}
		set
		{
			vm_product previousValue = this._vm_product.Entity;
			if (((previousValue != value) 
						|| (this._vm_product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._vm_product.Entity = null;
					previousValue.vm_pics.Remove(this);
				}
				this._vm_product.Entity = value;
				if ((value != null))
				{
					value.vm_pics.Add(this);
					this._product_id = value.id;
				}
				else
				{
					this._product_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("vm_product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vm_product")]
public partial class vm_product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _name;
	
	private System.Nullable<int> _movjodi;
	
	private int _price;
	
	private string _detail;
	
	private int _cat_id;
	
	private int _brand_id;
	
	private string _status;
	
	private EntitySet<vm_orderlist> _vm_orderlists;
	
	private EntitySet<vm_pic> _vm_pics;
	
	private EntityRef<vm_brand> _vm_brand;
	
	private EntityRef<vm_category> _vm_category;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmovjodiChanging(System.Nullable<int> value);
    partial void OnmovjodiChanged();
    partial void OnpriceChanging(int value);
    partial void OnpriceChanged();
    partial void OndetailChanging(string value);
    partial void OndetailChanged();
    partial void Oncat_idChanging(int value);
    partial void Oncat_idChanged();
    partial void Onbrand_idChanging(int value);
    partial void Onbrand_idChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public vm_product()
	{
		this._vm_orderlists = new EntitySet<vm_orderlist>(new Action<vm_orderlist>(this.attach_vm_orderlists), new Action<vm_orderlist>(this.detach_vm_orderlists));
		this._vm_pics = new EntitySet<vm_pic>(new Action<vm_pic>(this.attach_vm_pics), new Action<vm_pic>(this.detach_vm_pics));
		this._vm_brand = default(EntityRef<vm_brand>);
		this._vm_category = default(EntityRef<vm_category>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movjodi", DbType="Int")]
	public System.Nullable<int> movjodi
	{
		get
		{
			return this._movjodi;
		}
		set
		{
			if ((this._movjodi != value))
			{
				this.OnmovjodiChanging(value);
				this.SendPropertyChanging();
				this._movjodi = value;
				this.SendPropertyChanged("movjodi");
				this.OnmovjodiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int NOT NULL")]
	public int price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detail", DbType="NVarChar(50)")]
	public string detail
	{
		get
		{
			return this._detail;
		}
		set
		{
			if ((this._detail != value))
			{
				this.OndetailChanging(value);
				this.SendPropertyChanging();
				this._detail = value;
				this.SendPropertyChanged("detail");
				this.OndetailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int NOT NULL")]
	public int cat_id
	{
		get
		{
			return this._cat_id;
		}
		set
		{
			if ((this._cat_id != value))
			{
				if (this._vm_category.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncat_idChanging(value);
				this.SendPropertyChanging();
				this._cat_id = value;
				this.SendPropertyChanged("cat_id");
				this.Oncat_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_id", DbType="Int NOT NULL")]
	public int brand_id
	{
		get
		{
			return this._brand_id;
		}
		set
		{
			if ((this._brand_id != value))
			{
				if (this._vm_brand.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onbrand_idChanging(value);
				this.SendPropertyChanging();
				this._brand_id = value;
				this.SendPropertyChanged("brand_id");
				this.Onbrand_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(3)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_product_vm_orderlist", Storage="_vm_orderlists", ThisKey="id", OtherKey="product_id")]
	public EntitySet<vm_orderlist> vm_orderlists
	{
		get
		{
			return this._vm_orderlists;
		}
		set
		{
			this._vm_orderlists.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_product_vm_pic", Storage="_vm_pics", ThisKey="id", OtherKey="product_id")]
	public EntitySet<vm_pic> vm_pics
	{
		get
		{
			return this._vm_pics;
		}
		set
		{
			this._vm_pics.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_brand_vm_product", Storage="_vm_brand", ThisKey="brand_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public vm_brand vm_brand
	{
		get
		{
			return this._vm_brand.Entity;
		}
		set
		{
			vm_brand previousValue = this._vm_brand.Entity;
			if (((previousValue != value) 
						|| (this._vm_brand.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._vm_brand.Entity = null;
					previousValue.vm_products.Remove(this);
				}
				this._vm_brand.Entity = value;
				if ((value != null))
				{
					value.vm_products.Add(this);
					this._brand_id = value.id;
				}
				else
				{
					this._brand_id = default(int);
				}
				this.SendPropertyChanged("vm_brand");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vm_category_vm_product", Storage="_vm_category", ThisKey="cat_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public vm_category vm_category
	{
		get
		{
			return this._vm_category.Entity;
		}
		set
		{
			vm_category previousValue = this._vm_category.Entity;
			if (((previousValue != value) 
						|| (this._vm_category.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._vm_category.Entity = null;
					previousValue.vm_products.Remove(this);
				}
				this._vm_category.Entity = value;
				if ((value != null))
				{
					value.vm_products.Add(this);
					this._cat_id = value.id;
				}
				else
				{
					this._cat_id = default(int);
				}
				this.SendPropertyChanged("vm_category");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_vm_orderlists(vm_orderlist entity)
	{
		this.SendPropertyChanging();
		entity.vm_product = this;
	}
	
	private void detach_vm_orderlists(vm_orderlist entity)
	{
		this.SendPropertyChanging();
		entity.vm_product = null;
	}
	
	private void attach_vm_pics(vm_pic entity)
	{
		this.SendPropertyChanging();
		entity.vm_product = this;
	}
	
	private void detach_vm_pics(vm_pic entity)
	{
		this.SendPropertyChanging();
		entity.vm_product = null;
	}
}
#pragma warning restore 1591
